/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import tubes.halamanutama;
import tubes.koneksidb;

/**
 *
 * @author ROG GL552VX
 */
public class adminform extends javax.swing.JFrame {
    DefaultTableModel model;
    Database dbtubes = new Database("localhost", "root", "");
    /**
     * Creates new form adminform
     */
    koneksidb konek = new koneksidb();
    public adminform() {
        initComponents();
        String []judul={"ID Laundry","Nama", "Tanggal Masuk", "Tanggal Selesai", "Total Berat", "Jenis Pakaian", "Total Harga"};
        model = new DefaultTableModel(judul,0);
        table.setModel(model);
        
        setLocationRelativeTo(null);
        showdata();
    }
    
    void showdata(){
       Connection con = konek.getConnection();
       Statement st;
       ResultSet rs;
       String query="SELECT * FROM admin";
       model=(DefaultTableModel) table.getModel();
       try{
           st=con.createStatement();
           rs=st.executeQuery(query);
           model.setRowCount(0);
           Object[] row = new Object[7];
           while(rs.next()){
               row[0]=rs.getString("id_laundry");
               row[1]=rs.getString("nama_pelanggan");
               row[2]=rs.getString("tgl_masuk");
               row[3]=rs.getString("tgl_keluar");
               row[4]=rs.getString("berat");
               row[5]=rs.getString("jenispakaian");
               row[6]=rs.getInt("harga");
               model.addRow(row);
           }
       }catch(SQLException e){
           e.printStackTrace();
       }
    }
    public void pilih () throws ParseException {
        int i = table.getSelectedRow();
        if(i == -1){
            return;
        }
        idlaundry.setText(""+model.getValueAt(i, 0));
        namapelanggan.setText(""+model.getValueAt(i, 1));
        tglmasuk.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(String.valueOf(model.getValueAt(i, 2))));
        tglkeluar.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(String.valueOf(model.getValueAt(i, 3))));
        berat.setText(""+model.getValueAt(i, 4));
        jenispakaian.setSelectedItem(""+model.getValueAt(i, 5));
    }
    
     public void reset(){
        namapelanggan.setText("");
        tglmasuk.setDateFormatString("");
        tglkeluar.setDateFormatString("");
        idlaundry.setText("");
        berat.setText("");
        harga.setText("");
        jenispakaian.setSelectedItem("");
     }
     
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namapelanggan = new javax.swing.JTextField();
        berat = new javax.swing.JTextField();
        jenispakaian = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        idlaundry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        input = new javax.swing.JButton();
        ganti = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        harga = new java.awt.Label();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tglmasuk = new com.toedter.calendar.JDateChooser();
        tglkeluar = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(162, 222, 208));

        jLabel2.setText("Nama Pelanggan");

        jLabel3.setText("Tanggal Masuk");

        jLabel4.setText("Tanggal Selesai");

        jLabel5.setText("Jenis Pakaian");

        jLabel6.setText("Total Berat");

        jLabel7.setText("Total Harga");

        berat.setText("0");
        berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratActionPerformed(evt);
            }
        });

        jenispakaian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Campur", "Selimut", "Seprai", "Jacket" }));
        jenispakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenispakaianActionPerformed(evt);
            }
        });

        jLabel8.setText("ID Laundry");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        input.setIcon(new javax.swing.ImageIcon("D:\\Dzaky Tugas\\ITERA\\Semester 4\\Pemrograman Berorientasi Objek\\Tugas Besar\\new tubes\\new tubes\\src\\gambar\\add-button.png")); // NOI18N
        input.setText("Tambah");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        ganti.setIcon(new javax.swing.ImageIcon("D:\\Dzaky Tugas\\ITERA\\Semester 4\\Pemrograman Berorientasi Objek\\Tugas Besar\\new tubes\\new tubes\\src\\gambar\\couple-of-arrows-changing-places.png")); // NOI18N
        ganti.setText("Ganti");
        ganti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gantiActionPerformed(evt);
            }
        });

        hapus.setIcon(new javax.swing.ImageIcon("D:\\Dzaky Tugas\\ITERA\\Semester 4\\Pemrograman Berorientasi Objek\\Tugas Besar\\new tubes\\new tubes\\src\\gambar\\rubbish-bin.png")); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        harga.setBackground(new java.awt.Color(204, 204, 204));

        reset.setIcon(new javax.swing.ImageIcon("D:\\Dzaky Tugas\\ITERA\\Semester 4\\Pemrograman Berorientasi Objek\\Tugas Besar\\new tubes\\new tubes\\src\\gambar\\sync.png")); // NOI18N
        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon("D:\\Dzaky Tugas\\ITERA\\Semester 4\\Pemrograman Berorientasi Objek\\Tugas Besar\\new tubes\\new tubes\\src\\gambar\\reply.png")); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(108, 122, 137));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ganti, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hapus)
                        .addGap(18, 18, 18)
                        .addComponent(reset)
                        .addGap(18, 18, 18)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namapelanggan)
                            .addComponent(berat)
                            .addComponent(jenispakaian, 0, 244, Short.MAX_VALUE)
                            .addComponent(idlaundry)
                            .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tglmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tglkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(tglkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jenispakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input)
                    .addComponent(ganti)
                    .addComponent(hapus)
                    .addComponent(reset)
                    .addComponent(back))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratActionPerformed

    private void jenispakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenispakaianActionPerformed
        // TODO add your handling code here:
        String jumlahberat = this.berat.getText();
        int hargacampur = 4000;
        int hargaselimut = 15000;
        int hargaseprai = 10000;
        int hargajacket = 6000;
        double a = Double.parseDouble(jumlahberat);
        
        if(jenispakaian.getSelectedItem() == "Campur"){
            int c = (int) (a * hargacampur);
            harga.setText(""+c);
            
        } else if(jenispakaian.getSelectedItem() == "Selimut"){
            int c = (int) (a * hargaselimut);
            harga.setText(""+c);
        } else if(jenispakaian.getSelectedItem() == "Seprai"){
            int c = (int) (a * hargaseprai);
            harga.setText(""+c);
        } else if(jenispakaian.getSelectedItem() == "Jacket"){
            int c = (int) (a * hargajacket);
            harga.setText(""+c);
        }
        
    }//GEN-LAST:event_jenispakaianActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        tglmasuk.getDate();
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String query = "INSERT INTO admin (nama_pelanggan, tgl_masuk, tgl_keluar, id_laundry, berat, jenispakaian, harga)"
                + " VALUES ('"
                + namapelanggan.getText() + "','" 
                + date_format.format(tglmasuk.getDate()) + "','"
                + date_format.format(tglkeluar.getDate()) + "','"
                + idlaundry.getText() + "','"
                + Integer.parseInt(berat.getText()) + "','"
                + jenispakaian.getSelectedItem() + "','"
                + Integer.parseInt(harga.getText()) + "')";
        dbtubes.isiData(query);
        JOptionPane.showMessageDialog(null, "Data Berhasil ditambahkan");
        showdata();
    }//GEN-LAST:event_inputActionPerformed

    private void gantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gantiActionPerformed
        // TODO add your handling code here:
        tglmasuk.getDate();
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String query = "UPDATE admin SET nama_pelanggan='" + namapelanggan.getText() + 
                "', tgl_masuk='" + date_format.format(tglmasuk.getDate()) + 
                "', tgl_keluar='" + date_format.format(tglkeluar.getDate()) + 
                "', berat=" + Integer.parseInt(berat.getText()) + 
                ", jenispakaian='" + jenispakaian.getSelectedItem() + 
                "', harga=" + Integer.parseInt(harga.getText()) + 
                " WHERE id_laundry='" + idlaundry.getText() + "'";
        dbtubes.isiData(query);
        JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
        showdata();
    }//GEN-LAST:event_gantiActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            // TODO add your handling code here:
            pilih();
        } catch (ParseException ex) {
            Logger.getLogger(adminform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        model.removeRow(table.getSelectedRow());
        String query = "DELETE FROM admin WHERE id_laundry = '" + idlaundry.getText() + "'";
        dbtubes.isiData(query);
        reset();
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
    }//GEN-LAST:event_hapusActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new halamanutama().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminform().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField berat;
    private javax.swing.JButton ganti;
    private javax.swing.JButton hapus;
    private java.awt.Label harga;
    private javax.swing.JTextField idlaundry;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenispakaian;
    private javax.swing.JTextField namapelanggan;
    private javax.swing.JButton reset;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser tglkeluar;
    private com.toedter.calendar.JDateChooser tglmasuk;
    // End of variables declaration//GEN-END:variables

    private void data() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}